# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

version: '3.8'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://site_user:senha123@db:5432/site_info_2025
      ADMIN_PASSWORD: senha123
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17.5
    container_name: site_info_postgres
    restart: always
    environment:
      POSTGRES_USER: site_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: site_info_2025
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:

